---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app budge
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      # https://hub.docker.com/r/linuxserver/budge
      repository: lscr.io/linuxserver/budge
      tag: 0.0.9
    env:
      TZ: "${TIMEZONE}"
      PUID: "${SECURITY_CONTEXT_RUN_AS_USER}"
      PGID: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
    hostname: *app
    service:
      main:
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        storageClass: zfs-nfs
        mountPath: /config
        size: 1Gi
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:currency-usd
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
