---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./influxdb2-output.sops.yaml
  - ./telegraf-input-vsphere.sops.yaml
  - ./telegraf-input-ping.sops.yaml
