apiVersion: v1
kind: Secret
metadata:
    name: telegraf-ping-input
    namespace: monitoring
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    ping.conf: ENC[AES256_GCM,data:3zRPj5Qaf6JxSLp3q5+tGlO/X97bhVE3+ZgnqUpgCxIvzT5dGJbpLXNGGa4CENWek8o22dhllT3vxFfXI69OIgqtL3TtlSJJhtBzrOmU0JDfUoj9qo8fqoFqKp4GqW4a8mzjE2aYIfwnLzKsVeZpqLMTmY7AKaPnl7in8umvW0OvxDpo+UACSs+P0ko8LkvAIvSDAP4+4qGSFWZxvHJnbdoTjA5kySaFlOZk9mJjB82GRhod0B1+lLTm/Lo6PsccC5SZ0QJegVex+5rGJ1xYshclV/DKAKEigxRitK/+oirMmMqr/hUXIqsP3L6qbcbd7jcavKFq,iv:Iq5yIU7IXQhzJvsF5ssJUmztmBM4ehGyHy48aRM5zdI=,tag:y6dTYovShUYfZp87K8JVCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd1BTK0hpTnNBWlZmaENT
            L3BsZ1AreU51NUVvR0lNTnlydDljL1dBZWhZClozRUw0ZWVUaG9Tc1ptMEsybFN3
            QkJ0WHFZTmRhS0FTUTZJVHJacHNQR0UKLS0tIEVEQlFGbUhCb2tZbTY2RU9UVGZQ
            a2dIUjdkMWFPVlUySzJodEFFUjdRdzQKfIDL3R6/9ymAsCb3y1bodj5DmI0z13Qg
            y1+uJePadc1yTXSg3fk49VVLT/FoiCcGJFzkIjAV+dfI8uZj+nvrjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T18:44:05Z"
    mac: ENC[AES256_GCM,data:gegSPvx91UlPEfFkmNOnDZG05WraK+UEux/fiqHgRgtTfelwxBvYkhZuCBpaiLVZ3IYVaJF11Wl7MGmQfDKUmbgVteW6zcUKMGkrNPoN6SVBKySQSg3yLoolB5MtEI/GpJ724Gz6OmjeFS5e2hw5p6c/QhLc00c3KQ4XXmxQhvQ=,iv:f66Z6jBwQW+TUyQLzDir5KWIgTsEV4AxCU0x0KDLV7Y=,tag:XtlNuWDnH4Q0zYK1HfW5Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
