---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      mosquitto:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.19
              pullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              [
                "cp /data/mosquitto_secret/* /data/external_config/ && chmod 0700 /data/external_config/* && mosquitto_passwd -U /data/external_config/mosquitto_pwd",
              ]
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.19
    defaultPodOptions:
      hostname: *app
      securityContext:
        runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
        runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "{{ .Release.Name }}.${SECRET_DOMAIN}"
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 1883
    persistence:
      config:
        enabled: true
        storageClass: zfs-nfs
        globalMounts:
          - path: /data
        accessMode: ReadWriteOnce
        size: 512Mi
      config-file:
        enabled: true
        type: configMap
        name: mosquitto-configmap # overriden by kustomizeconfig
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      secret-file:
        enabled: true
        type: secret
        name: mosquitto-secret
        globalMounts:
          - path: /data/mosquitto_secret/mosquitto_pwd
            subPath: mosquitto_pwd
            readOnly: true
      external-config:
        enabled: true
        type: emptyDir
        advancedMounts:
          mosquitto:
            01-init-config:
              - path: /data/external_config
            app:
              - path: /mosquitto/external_config
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
