apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: influxdb-data
  mountOptions:
    - nfsvers=4.1
    - noatime
  nfs:
    path: "/warehouse/services/influxdb2"
    server: "${NFS_SERVER}"
  claimRef:
    name: influxdb-pvc
    namespace: monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: influxdb-data
  volumeName: influxdb-pv
  resources:
    requests:
      storage: 1Mi
