apiVersion: v1
kind: Secret
metadata:
    name: forgejo-postgres-secret
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LH7o+vroOw==,iv:on08QUfplFHm4pNDuZ195tsn7fHdZq0ArKil25HOxb8=,tag:PwFVft7Zwu29oSDQ2JdUFA==,type:str]
    password: ENC[AES256_GCM,data:wxnwkCinUXirWDkl1EfiOVJs1oV+tkyP2+HpvkynJs4=,iv:9MEJ3cK/NbNgRvZV/ALb5vP6g9tsDc5SMBgwr5Vjs5s=,tag:z5eI1VBon7ent20meJsc0Q==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVXNFc080Y3F4dkppU1pI
            ckdIdDVxRDdmdVA1bHU0dEtrSE1vM0s4dW5NCklNajVhS3JKNElKSVQ2UkRiSVRF
            bllGVitpMTlOZ2c1RFMyQmc5aTJCQnMKLS0tIGVWQ3ZjaktWSHl2V2NNdDRreDN6
            WjhIdlpkN0c1UExRNGV6KzIxa1dUUWMK7UoxogBnJKrR4FBTn9hokAszMSSkia0T
            6i/NDsthQOYvlBgoWaaaATl7Nt5rCxToBPS2GUMlrS8sKr/Jo9cp7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T02:21:41Z"
    mac: ENC[AES256_GCM,data:H25FAGK5zG0tjQAYN0xZc1KOLHCU6rW568/pJzBUfynWVxI4K/iVEJOoi4KzuJ6JLV3OwK4lBm6salYTIK3gp5qHXYrNIBLv7DI3Z2ubEMv+TiJIeByDGerBY+aCGdTY0IkbI+qFLmeS+JobK7xXN5QwerX4pVpkXpYGg3jjO34=,iv:9C4DYAcQ0jLrhPj0cTWDowza0ddoEdoRfP9T3LwTRSE=,tag:f8Nv0LLnVv4XWaHu/D2cMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
