---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Release.Name }}.${SECRET_DOMAIN}"
    gatus.home-operations.com/enabled: "true"
    gatus.home-operations.com/endpoint: |
      name: postgres
      group: infrastructure
      url: tcp://postgres16-rw.postgres.svc.cluster.local:5432
      interval: 1m
      conditions:
        - "[CONNECTED] == true"
      alerts:
        - type: pushover
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    role: primary
