---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

parameters:
  storage: "lvm"
  vgpattern: "ebsvg|10wpl-k8s-worker-[0-9]+-vg"
  thinProvision: "yes"

provisioner: local.csi.openebs.io
allowedTopologgies:
  matchLabelExpressions:
    key: openebs.io/lvmvg
    values: nvme
