---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Delete

parameters:
  storage: "lvm"
  vgpattern: "ebsvg"
  thinProvision: "yes"

provisioner: local.csi.openebs.io
allowedTopologgies:
  matchLabelExpressions:
    key: openebs.io/lvmvg
    values: nvme
