---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP}-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: ${APP}
        group: infrastructure
        url: https://s3.${SECRET_DOMAIN}/minio/health/live
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
          - "[STATUS] == 200"
        client:
          insecure: true
        alerts:
          - type: pushover
