# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:x9Hc4vDGtGh9JNbSHGn5ZgHPSbgiPxbvFmS7b5QR/ME=,iv:q0s8Zj3PKjWH/rSzRfhBBosVPreVkd91s3WYPpa7jo8=,tag:WWiqgmCj03G/k7r0EOfqDg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:9gKvy3XMz/vGXant7IFJLPVA4PvyS2gJV6EuLIGJlrM=,iv:wHLuDELCIkYzBPoRyL0UICFH+WY6BBeU31LJ6nBARMg=,tag:+0SRoBWPwFAJ5hhMdBnIOA==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTczBUOGhpaWhiMTFTOTBq
            WEN1NUkvS0dZKzFGKzJYalF0QWg4alpkVkNJCmZXd0NuQnArWUhWbGNZZDg1Y1Bu
            Ull4S1JJeG5FZGVjbG9QQUlxZlk1cU0KLS0tIENMdmtOdjJuMjNuTElVd3RVUEFH
            U28rZFg4VWxIUnFFY1VGdmRZWUlmeW8KqM9ESjZwhhjJNcCcILx1Bw3hRDKnbOkp
            I19r9vkSnNfNPpz7VM8pUB/NE7gJrEVC7IyVUvekuN+EzIlUN2VFAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T01:45:40Z"
    mac: ENC[AES256_GCM,data:nTqw7aDB2vCqCWm3o8JDMlKz3zhk4jj0SrQHAGAUrWBUwJzuUjjyWjqjdb5yAAMinOe5BeDh067iWIRcZO/GHFNBM9TEy+2ZghKNY36LDoM+LlI5AFrwqJ5aghwnSOGgAWE07ed+n1AuKi1eI6n2D/Vo6J6iltXlHe0wHyqwFyk=,iv:GHr2dQsxsFXAWcR3O+UMd+Nbdy+FEmkbUfiOU7BpetQ=,tag:2T8BpDj3p56juA4Y3tJCDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
