---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr
      tag: 4.0.4.1491@sha256:9c78b3a37af6e814062e4a631c25ad181c800ae11d21acdfd26c843da9e4a42e
    env:
      TZ: "${TIMEZONE}"
    hostname: *app
    service:
      main:
        ports:
          http:
            port: 8989
    podSecurityContext:
      runAsUser: "${MEDIA_SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${MEDIA_SECURITY_CONTEXT_RUN_AS_GROUP}"
    persistence:
      config:
        enabled: true
        storageClass: zfs-nfs
        mountPath: /config
        size: 10Gi
      movies:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            path: /warehouse/media/tv
            server: ${NFS_SERVER}
        mountPath: /tv
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
