# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: asterisk-secret
    namespace: default
stringData:
    manager.conf: ENC[AES256_GCM,data:AkoHzhiRsgAuVnrpCq/I9ucFCAohfC32INqv9LHpZ1bgLZVB6vwuaL8plbVLZibXaneyLpdM9ZaxcYXQyztuPgwoV7JfQmRUAOMpDigX5bdMk/oT29ElrbMeyB8mAf8i1P4sVPDuR7DMAF8InU8hvzCZ/zqNa6sGlyBeGrztayeXXnI//fps9DCKwxYadN5PneTRw8pJBRt2tNw1zuMZPC8K6rIQCuPTCOzZoq776Zz35Lh6pnuHpQqTTwp48u+2GBjeTjz+7MQ+p3zVTXhJ3cMafzQddh5aNnQvjnuo6vaxxRArchbK5c0TjhK8Hm63cNsoa6pfT8AzkwcVaQJEAyK+Ro9wvrcjbsVS8VP0cROJDuBmPzXdXI8k,iv:Z/XpKm7WAoRSh6syAA3Nwx8Szcmu4yqpqVmD23yKLkQ=,tag:TlF996FJGWZM3GBKpQxleQ==,type:str]
    pjsip-auth.conf: ENC[AES256_GCM,data:HSnTUFZJwuPMX1x9iX4Wf263PPfc4yzbKhvsMY3vNGBbZBqWxpPm4nGSPu5JXbQb2RZsRPHone05eUy0oQjc8sJyBlwnkPjFl1CbtFHMIJWlP6mG14HjXVD04EID6CiRQyouWChuSIhcN8YyzlDhnZ025cOGx7bAMHwP+Inj5+Ru6srGvIfcSJ9a+jIDpOPTXy2bjqqb7TJU/gaijn4UoGIiwXqA4R6JxhvY4UoO0cIXBwduuNg3coABIqG86CQw4qhgQYpiXFpnSv4Tgh9RqE5Pc78006jKV5K8xNa3CUo89TOfYEhGfDZvL2AvtiymFCeqwDfPZCNW2zGPn9cGjyO0u00vA0YWuTPOGr39fN026+nFsCRseIaUfS11QR6C1zDjSF3XOF7Fo/gMtC452w81KMSDXs7OpwfcmXtUpOpg1RpdPkGdiuJYm7Z4ojBdEm08BeR826zG+Ya2X+qO1UpoXasfXUKQ/pTQFtH0Nl5vQxKzQBiGhH0pbOIwrPbuPlLJbs7pWUXJydi7TF4ucmLv5IiKK7gL7vmaZzEQZN08tyIQJjIiB3fWBeekHiIPA5SgYo9j0JUppoRv04fC+mGeElooJC4E/rMRK8ind+sWHIfW+/a27VLWdsvWaCfLJV4X5KdgIe8aJrobQDZezVo2tV1I2Hr8K7x5Z36V7NEgA5H1EKMS1DyuBvHGCuSKchXTHveTS3RfmbGCJQPgT0iFtIqpIB9gojsOtxjsn2DdeAP6kG2ntouuw3rMOOsdO8UTwNUngNEJC3oHdo/HeBBGHWMQ3qUmqquuDEp07J0rwES70a8lIYGnYRVUQsUj5SLWce29INfZcDQFNxz9OKIrAgrKt89N3IgTUvV3/HX8O55qf5Bw/AFkUiZsZi587AImLz0opgWB++I1GC5uz0d1yPp4p/hZvjTiBwXhI+byl4RUk0F3cNPVo+AJzV7eCpwfH9c4Yql8h6AuIQ71pahn5NxxXHo+HvhlS+Ees6dYATa60p+vJkxQcH0g8gUJeYLgS5dPlvi8XL4vBOfsi94UoOC9UvNC49n4eCzn5/R4wnFMpFhUMTvRkRSVdTg73qN+vr2HXZbKyrKJN63GWg5lkVEn83Yp4/mKj+/vHarud34H8BjLA/byBMvyLKFZcvG+f2qRERqO4tomTgFPRk3SqtzUz+sS791hnkUzIzxkkHLXWZyn9nhAfWwfqb8wvKpS4FH+IhY5D94F8Vnjys5ROLqmtX6y7EM/66vfelnsero8RQ==,iv:xrLo+nrc9bLieqce6ojt9j8tUdAuDH27OryxDcshAZ0=,tag:9weog/EeflaRETsp2tnNUg==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c0dpa1QvTXJvTTVYc2U2
            NGc5MDFDZjRSbktGdFltTnRkOUhTR21ONGxVCkhJQ1hNTkJMSDk2Zzh1dm9pNkF0
            NzVBWjBna0VWaSt0LzNtVDhnVGNpYVkKLS0tIHdlcTlBZkVWNC9OOC94SWlML2di
            dEpaZ0t5WVR6MG5rMjFxR2hndkFMcXcKBsVtiGTD4pw73yrhLtOPfSJcbejAlPwv
            iOp5xqgmiXfadfSyjIv4ZQrkOs40COryLTZl8Als5GcpjX017ErZOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T00:57:12Z"
    mac: ENC[AES256_GCM,data:CvvLckhcbTZ9LRZ3i7R908rJAvXFPQF1mnwWVlm9epDS1N3cT/C50j2Lg0h3h+uVA+XarpvpESV39do2Pf009EGKFm1sO/vbhYpFqetasWW1OfBHHCg2tfoDfaM/viCVLLEJSAYQbsOlsmOrk+Ld88rYX0lS+pUD/xMZx6LMONc=,iv:b787DyKmraAibLQ+VbqNKYBmlxcDxoQrmciimjdIFpk=,tag:MXZfw9wOQ0PzQAWQt9woNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
