# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: asterisk-secret
    namespace: default
stringData:
    manager.conf: ENC[AES256_GCM,data:n/x3wpwDurdzKTIKARH3XJWnfvVIS9x4ok4ikfhUk4NHg/cKPJZWXONPgvF/bMBt7rTWD+ymkk4EIDLwpsVZJtg9dZ+2wbBXrKdbiHegS33Ck8jz4pAOm6PF3muONHFiOCLbotIt928pZ54Y2KzPd1tYVKOzwUx86RVSWcBcK8KQ0/PVP90qe1rvrBJrcYV+pKXOZ1Qjsre8XKOHJHgfpJ+szTQmTTOx8VoGtX10lfNtdeThjAZaaEZLKclpMbK+t/m8GtQkYImx8lbANc33KV4U0I4ajk/NtF9L4odxPloyTbXdmfMhSya/gtgk0YvLjqdsAi9MuyrqmDw4BAKfhfvlJmt99xKK2jtL3EEs//raeguQ7Nlzj1Um,iv:g7fJ3EegafO+gG1paLMvGGPF6NfdFv9WdK+RgJsVbq8=,tag:mkF8tx78frq88BAJJGdubA==,type:str]
    sip-peers.conf: ENC[AES256_GCM,data:E5sc8WL8uD9L04TbKONwX3afIfBvw/jDySndcSHVjGAvKWqIHOcaZpBEKUgKUs9Yxw5CET+Ix75IYjnyV810CH6ukfBWNhm481sm5/vHBIXYgdPHOhHgKcNFQ6ZJygyBoKd2gojhTkCjS2a/v/E7/CRFOmtA002QuqC5N0galGngFT03e4ShpXdrxwar/wvnG9g5QO4xmw/aDMHRDyeAZBSqZBGRlWc37APbodklbWNqoXmGXc5JRiMTJr1AJX/ZJpceok+4x1qM1MGqsB9HvWiSk8cUfravODs5U/brDA==,iv:oug6EerrNXuvep8E0E8HALoaMPXBdVlUfRbuzVnYTjs=,tag:5cIi9fK7UDyb1eaG0ILBSA==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Mk54b2N2ZTNDUVhuMXNy
            bUgzc2F2bEorMEQyaEVjeXZrUnFFVlU5NTJBClZheDNBVGdrYUVVM0dJTWJJSE5i
            SlhkNHpBblBmbkduQjFGUlhXZ3A5MFkKLS0tIFV3c0VyeGIyRHA2UW9iME84NmtC
            bDdQc0RVR1lCQWFFZ1k0R0RTN3IvWDQKkUcPEjdTh+czmNcG4WUgbwevudTjw955
            giao7xhbbwdLDuoAFRsjNfy7dV9WmXYGN55S3y7FI8bnF/emsM9hLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T02:02:34Z"
    mac: ENC[AES256_GCM,data:0mUy/UofrDCg+FzIZh1drQpEONQulOPYAeBX5efEmwS2Yx4GcDlB2sq+xEBbTj/Uzj26pK8fwVZYe72+QYsym/LX+ZuobFwHmMeAsb3KuwAvqy+zAJKzbkgCE4JmYSy9L6PUyZiBc9CheIO7aA8zmETe4voi8wbXnBIhPj9FBA0=,iv:0O6gY5/G/UzRoGnT/NPcGCXxS48pIPL9OZjbqFvIBoE=,tag:IWFdbdUEVo3YErqQ+dFo2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
