---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./atuin/ks.yaml
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./mosquitto/ks.yaml
  - ./minio/ks.yaml
  - ./frigate/ks.yaml
