apiVersion: v1
kind: Secret
metadata:
    name: forgejo-database-secret
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CAjlUU/+SA==,iv:FpbpiYrbg+IQJcbDYs+7keI9PNccQvHEKkgM8iL0okk=,tag:pwEZP58FTICTuIW6fQtW4A==,type:str]
    password: ENC[AES256_GCM,data:biqI8dOv3jJNFK+lCHbQAhpGTfykqcCrKqSNzUnE3tM=,iv:gg3MpnJLMh9trvQLe3QNUKPbo/b9kAdamxGUsce4Sdo=,tag:hLWDfT43VfdbVl8wRRhSrg==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZElEbGFMUGZQc0lzS2d3
            ZWI4NDVHMHZNOUsvYXZEOVVMTDhnTkJCYmc4CkxtOEFHakR5eWJ3VzZwY3hIK2xL
            ekNkZDZZRkdWSkUzRzJObkt1bjN1UEEKLS0tIG9mK2VsMUkxZi9UTEVocXB3cXNY
            bWQ5SittazI4T3ppVzBsUG1JaWRLU28K0nUDHPPgtPCn1mu6RJ9UrE/zUg4QRlWO
            5eqlkZrRpUDSkocqQ/1mH86N1/C2hnVsET001Ad+R31748Mun0g+Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T16:22:02Z"
    mac: ENC[AES256_GCM,data:RleR3i6jXlwHZIL7DG3NuvRHheknZuqo7jrOyG4LoXQgZjs1uPagiauwJsety81/viNBrV/4f9dOsqOEFWAclG4NUQ9dHXsZTQ+xdxG49MJ8/bU25oOOFSnQZdrQIyfta1wZZp/gH7wnpZnk0819b07aeWP1BGjCFzNPcadowFY=,iv:hxHhEoVDtF2bV1CN8T3rCBVI4zMBK4nVCftGGGIs7A8=,tag:xES9JTMCxb65F0jJe2RuMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DUx4+U8=,iv:UwlWJK0mGUiZ2aP85FplXFQBWJzzmH9va2IOjk5PslU=,tag:4pZTov2clXwsgXLPIibNlg==,type:str]
    password: ENC[AES256_GCM,data:Mx8t8Dd/GeeJWSbuYa+Nd5YHQ8K/ezBvtbTNF9qHW1c=,iv:XJf6HX1ygOn88DaDWR1D334en0US1myRX0BysMS8L6w=,tag:9+Rpgc6NuxwBcq+y94eMZQ==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZElEbGFMUGZQc0lzS2d3
            ZWI4NDVHMHZNOUsvYXZEOVVMTDhnTkJCYmc4CkxtOEFHakR5eWJ3VzZwY3hIK2xL
            ekNkZDZZRkdWSkUzRzJObkt1bjN1UEEKLS0tIG9mK2VsMUkxZi9UTEVocXB3cXNY
            bWQ5SittazI4T3ppVzBsUG1JaWRLU28K0nUDHPPgtPCn1mu6RJ9UrE/zUg4QRlWO
            5eqlkZrRpUDSkocqQ/1mH86N1/C2hnVsET001Ad+R31748Mun0g+Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T16:22:02Z"
    mac: ENC[AES256_GCM,data:RleR3i6jXlwHZIL7DG3NuvRHheknZuqo7jrOyG4LoXQgZjs1uPagiauwJsety81/viNBrV/4f9dOsqOEFWAclG4NUQ9dHXsZTQ+xdxG49MJ8/bU25oOOFSnQZdrQIyfta1wZZp/gH7wnpZnk0819b07aeWP1BGjCFzNPcadowFY=,iv:hxHhEoVDtF2bV1CN8T3rCBVI4zMBK4nVCftGGGIs7A8=,tag:xES9JTMCxb65F0jJe2RuMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-ldap-secret
    namespace: default
type: Opaque
stringData:
    bindDn: ENC[AES256_GCM,data:KxOqaBti+Jg7pLVKUT8OEM2fNnAgqI/9skpNv3bh0W+esQK4ooofYIulsuOGyLv1EoqX09MMwY2NQmg=,iv:0wAM6YYiYQ2NCtgdgs5jK9wMmhT0ROfLsdNr/hy7RM4=,tag:iH7UBA0un55/6/uXQjtyTw==,type:str]
    bindPassword: ENC[AES256_GCM,data:gSItLOk+hEafcrIRvXCC5+pjZwc=,iv:q8cZZdF9DqkoHC6iPUnYrvdh4MZEr4UYpdRrknpXel4=,tag:3g5VxH5qBredLfcYkoZMpg==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZElEbGFMUGZQc0lzS2d3
            ZWI4NDVHMHZNOUsvYXZEOVVMTDhnTkJCYmc4CkxtOEFHakR5eWJ3VzZwY3hIK2xL
            ekNkZDZZRkdWSkUzRzJObkt1bjN1UEEKLS0tIG9mK2VsMUkxZi9UTEVocXB3cXNY
            bWQ5SittazI4T3ppVzBsUG1JaWRLU28K0nUDHPPgtPCn1mu6RJ9UrE/zUg4QRlWO
            5eqlkZrRpUDSkocqQ/1mH86N1/C2hnVsET001Ad+R31748Mun0g+Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T16:22:02Z"
    mac: ENC[AES256_GCM,data:RleR3i6jXlwHZIL7DG3NuvRHheknZuqo7jrOyG4LoXQgZjs1uPagiauwJsety81/viNBrV/4f9dOsqOEFWAclG4NUQ9dHXsZTQ+xdxG49MJ8/bU25oOOFSnQZdrQIyfta1wZZp/gH7wnpZnk0819b07aeWP1BGjCFzNPcadowFY=,iv:hxHhEoVDtF2bV1CN8T3rCBVI4zMBK4nVCftGGGIs7A8=,tag:xES9JTMCxb65F0jJe2RuMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-s3-secret
    namespace: default
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:D+JvGpCut4ZeGrHl,iv:XSrZJ4wa3cfjMjqciDq6Rfm3QgrKOkncdLK0xVU3+vY=,tag:GSldEqsauSKhuXiblqhcsg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AVOaZkKbxVnk5dStEhikFTBknQ==,iv:Gd1ycGraRn4iJEnJ8MprNxEhrjmklxf78dWw2C8RNx0=,tag:WehGaxvCOXY8tTY/rE2UQQ==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZElEbGFMUGZQc0lzS2d3
            ZWI4NDVHMHZNOUsvYXZEOVVMTDhnTkJCYmc4CkxtOEFHakR5eWJ3VzZwY3hIK2xL
            ekNkZDZZRkdWSkUzRzJObkt1bjN1UEEKLS0tIG9mK2VsMUkxZi9UTEVocXB3cXNY
            bWQ5SittazI4T3ppVzBsUG1JaWRLU28K0nUDHPPgtPCn1mu6RJ9UrE/zUg4QRlWO
            5eqlkZrRpUDSkocqQ/1mH86N1/C2hnVsET001Ad+R31748Mun0g+Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T16:22:02Z"
    mac: ENC[AES256_GCM,data:RleR3i6jXlwHZIL7DG3NuvRHheknZuqo7jrOyG4LoXQgZjs1uPagiauwJsety81/viNBrV/4f9dOsqOEFWAclG4NUQ9dHXsZTQ+xdxG49MJ8/bU25oOOFSnQZdrQIyfta1wZZp/gH7wnpZnk0819b07aeWP1BGjCFzNPcadowFY=,iv:hxHhEoVDtF2bV1CN8T3rCBVI4zMBK4nVCftGGGIs7A8=,tag:xES9JTMCxb65F0jJe2RuMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
