---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      speedtest-exporter:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/miguelndecarvalho/speedtest-exporter
              tag: v3.5.4
            env:
              TZ: "${TIMEZONE}"
            resources:
              requests:
                cpu: 15m
                memory: 30Mi
              limits:
                memory: 50Mi
    service:
      app:
        controller: speedtest-exporter
        ports:
          http:
            port: 9798
    serviceMonitor:
      app:
        serviceName: speedtest-exporter
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 120m
            scrapeTimeout: 300s
