---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 4.7.5.7809@sha256:4a51f4903789b9f2263d2a8390e5044e45b4c4553b97fa68840eed2215541303
    env:
      TZ: "${TIMEZONE}"
    hostname: *app
    service:
      main:
        ports:
          http:
            port: 7878
    podSecurityContext:
      runAsUser: "${MEDIA_SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${MEDIA_SECURITY_CONTEXT_RUN_AS_GROUP}"
    persistence:
      config:
        enabled: true
        storageClass: zfs-nfs
        mountPath: /config
        size: 10Gi
      movies:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            path: "/warehouse/media/movies"
            server: "${NFS_SERVER}"
        mountPath: /movies
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:movie
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
