---
# Note: Gatus vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
web:
  port: $${WEB_PORT}
storage:
  type: postgres
  path: postgres://$${INIT_POSTGRES_USER}:$${INIT_POSTGRES_PASS}@$${INIT_POSTGRES_HOST}:5432/$${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
endpoints:
  - name: Router
    group: 10WPL-Infrastructure
    url: https://helgrind.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    client:
      insecure: true
    alerts:
      - type: pushover
  - name: Storage
    group: 10WPL-Infrastructure
    url: icmp://svellhjall.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: DC-2
    group: 10WPL-Infrastructure
    url: icmp://10wpl-dc2.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: Ingeitum
    group: 10WPL-Infrastructure
    url: https://ingeitum.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    client:
      insecure: true
    alerts:
      - type: pushover
  - name: UMR Switch
    group: 10WPL-Infrastructure
    url: icmp://10wpl_umr_sw0.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: Lab Switch
    group: 10WPL-Infrastructure
    url: icmp://10wpl-lab-sw0.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: WAP
    group: 10WPL-Infrastructure
    url: icmp://10wpl-wap.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: Router
    group: 40MCK-Infrastructure
    url: https://40mck-firewall1.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    client:
      insecure: true
    alerts:
      - type: pushover
  - name: Storage
    group: 40MCK-Infrastructure
    url: icmp://40mck-storage-1.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: Switch
    group: 40MCK-Infrastructure
    url: icmp://40mck-switch-0.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: WAP
    group: 40MCK-Infrastructure
    url: icmp://40mck-wap-0.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: Router Proxmox
    group: 40MCK-Infrastructure
    url: icmp://40mck-proxmox-0.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: Proxmox 1
    group: 40MCK-Infrastructure
    url: icmp://40mck-proxmox-1.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: DC-1
    group: 40MCK-Infrastructure
    url: icmp://40mck-dc1.${INTERNAL_DOMAIN}
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
alerting:
  pushover:
    title: Gatus
    application-token: $${PUSHOVER_TOKEN}
    user-key: $${PUSHOVER_USER_KEY}
    priority: 1
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
connectivity:
  checker:
    target: 8.8.8.8:53
    interval: 1m
