apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: monitoring
stringData:
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:EUV1tkgTiTcTbSL4COWxO9pUWJBk3gVwOYX0y7Ok,iv:2owINkbJqhlstOCEBGoZfre5Xg58o0/GJH/zwEMjG4E=,tag:+5ksP49hjBZ+8YpXcBvVaQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:C7MZQgtE9Ox4AzSB95n/1UUkbW4O6nsEYqofqy70,iv:fW3+3/s2OY/n0BHnKDKlJpLTbzHeEFlMwuGUKTWZK/E=,tag:gmlhaZymympQZ5rwMXXOdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU0FNcUcycEV2OU4vR2Vh
            RzlyUmxuVG9yTEdnMU5raUpXZEpFaGY2L0cwCkhPVnR3cisxQnBwdzZja1NMdUhM
            TUw0ZzJiUzFxRXJPYWlBNlBqVjdTeTgKLS0tIFpLTVNXc0RYWWRvZTI1V3BhSkdG
            dFY5QVdaVVYrNkE1U3k3RVpGK1d5L2sKhhfdRkloEBFmeMULz3UROiHkwDFnCJQv
            1IREk43gfI3+/Pkj4XiOcYO2Xh33Ccgt3OiJRwztGg0CCVq/Z8u1uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T02:27:56Z"
    mac: ENC[AES256_GCM,data:vawg4zmfcdLXvKaOlp2oKgHoULHinidO9t9/HL7asnkRTZ1zdWSM90mIZPVwGuhvtjieRqpotq08Q13zXmrcAcz6yCauFnCSP4BlA/ov7Fh/iBjHGLoJNQ5YpXyys6ChB2Fm0Vpl0WDOdUq7w0m3cEZecwoWA4OL04/EogzHnT8=,iv:DheugmbdS4nw3Y2p6WQWeC+ZRPyQc0BEMl1j7FXhbZc=,tag:g5oc1mWNrbFGEwv2lHXZgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
