apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3uWIsoalosOUSTLCY6hSSWM=,iv:cr5QDvfMWVoC/2U/6OwjEL1R6mRpy/phju/wUe/q2o8=,tag:M6tlRzE/3h80aWByFdpu3g==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:NK/cwpcttmSI+757zQ==,iv:dbLXeOUaFsKJyJAQAvqp4pRFyfjehiAJx5jN4jDip5s=,tag:TuCBdt+Z59Sb0amQurwYzA==,type:str]
    LDAP_SERVER: ENC[AES256_GCM,data:2Us2uH9aKupPmaIm,iv:Wrvtg1PRay5qF40eGWjgV8AJbwElU3F5kbtPzOZJtgA=,tag:aP/Z+aNsFyCTqUZkdayurA==,type:str]
    SECRET_ORGANIZATION: ENC[AES256_GCM,data:YqVstKKznFjv,iv:wujfWuPIcW0R3fdV9DOcD+jLI26y6NqdsHYXeSjRQjw=,tag:0d1l1lsT1Ouy0NF93sljBw==,type:str]
    SECRET_DOMAIN_DN: ENC[AES256_GCM,data:xuuyj6SAFDok1ORq9Isvq/S+nA==,iv:8g6HhscsccqA9eMbczHnzXQk6PkSUnB6z9k+vxMuYUM=,tag:uZBaggE7ozTpXD+alamWvA==,type:str]
    PRIVATE_DNS_SERVER: ENC[AES256_GCM,data:X5ZyyIUzRDBAjz3K,iv:5mmboqJTi/7sJeh/EkA+Bmmdac4xFakIOqvrFzcgQcE=,tag:Y9R+M8ahLGSZ59sVbG7XiA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
    MEDIA_SECURITY_CONTEXT_RUN_AS_USER: ENC[AES256_GCM,data:+NNyvyo=,iv:mytTWZEYeGTDlHHGcEOaI5jmcxt5UmyYHx8Mh4Ux/lY=,tag:HZ55SP/r9ljqZL+58POrlw==,type:str]
    MEDIA_SECURITY_CONTEXT_RUN_AS_GROUP: ENC[AES256_GCM,data:po6LV90=,iv:7EoBttuN8wv+ryAGmbQbVPoYH2VcDPbxNnsj8wOcvO0=,tag:9+cpVRNgrrrTSd+xB0UaHg==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:N4KBirGD8Dh7SZY0WmWzGNObpW33POvU,iv:cusILuCDDZMHM5Y+MLJw3IOIPz24fyWzmONcvEWyllA=,tag:gfPptibwysOddCAPbsw0GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbFFma2JRbG9QZTdoYkor
            MnVqbTQ2ZmJCdkkrOElZeEdkcTZVRndmaFNjCmZEQUtOZFRxazlvaDNrY2xvN3Zo
            Rm9ZaTNHUzFzU2M4Sm96T1NCZ2t2N1EKLS0tIHpiYlRIMHY0ZkQ2YWNUZGUxY00x
            amIwS0NZZ0RyZnN5S3FYNi90OHZHMXcKje7tj7u2e6aObklFUnMmYnH7Ey3W4DmJ
            E7ToHKPi+TbFk7WKaafOsHTLXPlr/C/bC5QS0Gw4ML1LmbV5Br7Fhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T17:53:10Z"
    mac: ENC[AES256_GCM,data:GE4Hbj3JSHhzQkNWGFBK4ijGsKMbY/l7YX05l0kgcs5ljWFznu1hwRJWd1hrAAypC/Dwt+z43tKQDmHWQwYCqZRkotwPUSx3NxsjxdIYDTaIB0Hg26X5Au5WAjYLfwGoSvg1DVH2vjOMS3WNxa8APu2naZfQq+V089/6x2LjDIA=,iv:45IlG4ux6HZ8nC8gQ75OZdRJMr1smL+jYXcuF8jxKsM=,tag:6yoCNFbXWYQAp7YiyFhDfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
