apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3uWIsoalosOUSTLCY6hSSWM=,iv:cr5QDvfMWVoC/2U/6OwjEL1R6mRpy/phju/wUe/q2o8=,tag:M6tlRzE/3h80aWByFdpu3g==,type:str]
    PRIVATE_DNS_SERVER: ENC[AES256_GCM,data:vjzmwk7x7BltPkC6,iv:W18tXqDBfz4lIC2ew7nTYUpDEYMIFp4jOT1vdYviDPA=,tag:ILRHDup/Xk4yOWz200pKNw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbFFma2JRbG9QZTdoYkor
            MnVqbTQ2ZmJCdkkrOElZeEdkcTZVRndmaFNjCmZEQUtOZFRxazlvaDNrY2xvN3Zo
            Rm9ZaTNHUzFzU2M4Sm96T1NCZ2t2N1EKLS0tIHpiYlRIMHY0ZkQ2YWNUZGUxY00x
            amIwS0NZZ0RyZnN5S3FYNi90OHZHMXcKje7tj7u2e6aObklFUnMmYnH7Ey3W4DmJ
            E7ToHKPi+TbFk7WKaafOsHTLXPlr/C/bC5QS0Gw4ML1LmbV5Br7Fhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-29T02:30:25Z"
    mac: ENC[AES256_GCM,data:F9E3TwFzcol1jH18iiH7PSlsqWpC40UuytAA+89426FrsKvug+QIPrf/gt6En4c0czdOG6SqWn2ywLHVJzgbKBVyVUJgsr3i5pFOVLOwYqIc8kC5CWR9SQ+hXU5sR55JNQqs0q4tSvUP6r+rv7SqZYkLw7kc1qowPVErlzJ2z1M=,iv:S1Y6sWv2MYn6jDxrOhKUCU5wHqPbbKnAN96cUpyTHWc=,tag:bn6GmftqxH5VL6Ikrq2aFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
