---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.16.135"
  METALLB_LB_RANGE: "192.168.16.120-192.168.16.130"
  METALLB_K8S_GATEWAY_ADDR: "192.168.16.120"
  METALLB_INGRESS_ADDR: "192.168.16.121"
  SECURITY_CONTEXT_RUN_AS_USER: "1000"
  SECURITY_CONTEXT_RUN_AS_GROUP: "1000"
  SECURITY_CONTEXT_FS_GROUP: "1000"
