[general]
static=yes
writeprotect=yes
clearglobalvars=no

[globals]
RING_TIMEOUT=25

[internal]
exten => 800,1,VoiceMailMain(${CALLERID(num)}@default)
 same => n,Hangup()

exten => 600,1,Dial(PJSIP/100&PJSIP/101&PJSIP/102&PJSIP/103&PJSIP/104&PJSIP/105&PJSIP/106&PJSIP/107&PJSIP/108&PJSIP/109,${RING_TIMEOUT})
 same => n,Hangup()

exten => _10X,1,Dial(PJSIP/${EXTEN},${RING_TIMEOUT})
 same => n,VoiceMail(${EXTEN}@default,u)
 same => n,Hangup()

exten => 100,hint,PJSIP/100
exten => 101,hint,PJSIP/101
exten => 102,hint,PJSIP/102
exten => 103,hint,PJSIP/103
exten => 104,hint,PJSIP/104
exten => 105,hint,PJSIP/105
exten => 106,hint,PJSIP/106
exten => 107,hint,PJSIP/107
exten => 108,hint,PJSIP/108
exten => 109,hint,PJSIP/109
