[modules]
autoload=yes
noload => res_pjsip.so
noload => chan_pjsip.so
noload => res_pjsip_acl.so
noload => res_pjsip_authenticator_digest.so
noload => res_pjsip_endpoint_identifier_ip.so
noload => res_pjsip_mwi.so
noload => res_pjsip_notify.so
noload => res_pjsip_outbound_publish.so
noload => res_pjsip_outbound_registration.so
noload => res_pjsip_publish_asterisk.so
noload => res_pjsip_pubsub.so
noload => res_pjsip_registrar.so
noload => res_pjsip_session.so
