#include "pjsip-auth.conf"

[global]
type=global
user_agent=10WPL Asterisk

[system]
type=system
timer_t1=500
timer_b=32000

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=${METALLB_ASTERISK_ADDR}
external_signaling_address=${METALLB_ASTERISK_ADDR}
local_net=10.0.0.0/8
local_net=172.16.0.0/12
local_net=192.168.0.0/16

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_media_address=${METALLB_ASTERISK_ADDR}
external_signaling_address=${METALLB_ASTERISK_ADDR}
local_net=10.0.0.0/8
local_net=172.16.0.0/12
local_net=192.168.0.0/16

[phone-endpoint](!)
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=alaw
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
transport=transport-udp
dtmf_mode=rfc4733
language=en

[phone-aor](!)
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=60

[100](phone-endpoint)
auth=auth100
aors=100
callerid=Phone 100 <100>

[100](phone-aor)

[101](phone-endpoint)
auth=auth101
aors=101
callerid=Phone 101 <101>

[101](phone-aor)

[102](phone-endpoint)
auth=auth102
aors=102
callerid=Phone 102 <102>

[102](phone-aor)

[103](phone-endpoint)
auth=auth103
aors=103
callerid=Phone 103 <103>

[103](phone-aor)

[104](phone-endpoint)
auth=auth104
aors=104
callerid=Phone 104 <104>

[104](phone-aor)

[105](phone-endpoint)
auth=auth105
aors=105
callerid=Phone 105 <105>

[105](phone-aor)

[106](phone-endpoint)
auth=auth106
aors=106
callerid=Phone 106 <106>

[106](phone-aor)

[107](phone-endpoint)
auth=auth107
aors=107
callerid=Phone 107 <107>

[107](phone-aor)

[108](phone-endpoint)
auth=auth108
aors=108
callerid=Phone 108 <108>

[108](phone-aor)

[109](phone-endpoint)
auth=auth109
aors=109
callerid=Phone 109 <109>

[109](phone-aor)
