[general]
context=internal
allowoverlap=no
udpbindaddr=0.0.0.0:5060
tcpenable=yes
tcpbindaddr=0.0.0.0:5060
transport=udp,tcp
externaladdr=${METALLB_ASTERISK_ADDR}
localnetwork=10.0.0.0/8
localnetwork=172.16.0.0/12
localnetwork=192.168.0.0/16
srvlookup=no
allowguest=no
alwaysauthreject=yes
videosupport=no
language=en
disallow=all
allow=ulaw
allow=alaw
rtptimeout=60
rtpholdtimeout=300

[phone](!)
type=peer
context=internal
host=dynamic
transport=tcp
nat=no
directmedia=no
identity=remote_party
diversion=yes
busywhendnd=yes
cisco=yes
pickupnotify=from,to
pickupnotifytimer=5
keepconference=no
multiadminconference=yes
huntgroupdefault=no
maxqualify=2000
qualifyexpires=60
allowsubscribe=yes
notifyhold=no
mailbox=100@default
disallow=all
allow=ulaw
allow=alaw

#include "sip-peers.conf"
