apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-secret
    namespace: monitoring
type: Opaque
stringData:
    LOKI_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:YiLKmxA8kB+CmF8nsKvpkj6ffG8=,iv:zmrPQLcnvbEpfl+jCnlqpUQX0+CjY5ofIzhs/aCKbWg=,tag:ajrxW2YHfMWSpg3tAjK2vw==,type:str]
    LOKI_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zS70rdMao3zzoP1Kv1qBQ/6k5MQI2Y0pZhX7Ko2E5a+BmR95oLMXnA==,iv:mwcsyqJEOKEnVJEJPECu+Qvr5e/sZPRMKZcixUF9LvI=,tag:1SIs0iKwJTcmzRTk94e79Q==,type:str]
sops:
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bG5qcmtPZnF2QjcwQUJW
            N2l0TXhsSFJpZGltWlAwQ2xHdGFlbHpGNEdzCldwMHBLQWk4cVZacm1zVWFFeGov
            LzJ3NVJ4SzZvdEhib1R3UEF1c1NoRG8KLS0tIHVTa2U2dm1nd09NcjVsd3pRaVJH
            TjRTcTBUcVUyYlpIMXp4dFdQc0Q4UWsKgXOcS4lcn3ib2EcwRT6z+CCOcERPAUqE
            5TpWeT4RIUjLUPT/5F//8gszp3+hwLSfELW12ooqLbPugZJ7F8sC4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T09:40:48Z"
    mac: ENC[AES256_GCM,data:WwFy8//StkVzrfVh/vjaVOV+bVK0QHbxPCAHtU3FMC3rmz8RmwQXMDHWg1Wg0lJzkEyFqquFWRbVJpzMvuSDInq1g/fR/HAel2oz0SqjZZe5idAaGOc++HcQxBW7TjOrtWcQKDfLQW+gmjb20YtH/YMuAiNMoHZ4JAewtFBWk3M=,iv:UNtD3WsOsTtgP5QYlTGkoL8aVqulPSvO6yww2tzQXoM=,tag:qKK1XW4jN2SWZLxStGIKQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
