# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: romm-secret
    namespace: media
stringData:
    DB_HOST: ENC[AES256_GCM,data:zVgfI7QttGjTP0n8cBNDxC7ftyWq/tsbSnFo033vq3OuGO8DUiPuUg==,iv:NL+57gpg+Aa8sFpuwmOlJbWRemdRsLIaz95LESPO758=,tag:KuAirdLwHxhcgtnsnIxw2Q==,type:str]
    DB_NAME: ENC[AES256_GCM,data:P8f8cQ==,iv:5Zm5i8PpvlHvQRMG8W9aYjt8diwvK5zExCJ/CBGwT/c=,tag:b2fwOfbYVExXaetBZSR8mA==,type:str]
    DB_USER: ENC[AES256_GCM,data:M96hvQ==,iv:qmzQZIboYdvGHAFvQ/9zXJvRvka+OWF2DhgC56nGeec=,tag:CRGY1pvCcPcrpjYhb2aScw==,type:str]
    DB_PASSWD: ENC[AES256_GCM,data:/bAKwQMAMgxi68oCMXIzF5HcqSLZ62EguDdSmkjvbo/4qxbuQrzOttcaQta3oIR5,iv:YrsIGQaly/04R/iJ9pOihGgriAkaDBcBZosttDfUTdc=,tag:8VQgZrs64wI2/onIijE7Pg==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:psdMpvT2KnNtZI05xcBEf8rUqtOABsKatHB75oNtaOMO1li6rB9PF+2XlYf/Tw62kH5WUAphuKP5PrSsFsnsvg==,iv:89XYqOrNW6UOtUKpo7PWJAVpJVjXb6h5dUSblk7MppQ=,tag:4D4wLuoYLFO6oyy51nwcGw==,type:str]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:KsczCYM76MCVg4yZT1JJIdKPsa+ReWRn2TcFbAlN,iv:vRD+Fz6LEDIXcjlrH4n6KdC4Knk8d9KsFBDh6gw/5Hc=,tag:aVDj7iECpB6R53tO6pZLpQ==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:GbSTjfH7G7WZ/9QKyhxX8a1ckII1PUXwLOcHfM+R,iv:SLzynAYzmFqCcxAYB0+cT2k2WszTlxSKrq0V8tS7SWg=,tag:WaNx3qPBalRT2jN3DpFWLg==,type:str]
    RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:f4K5u1564wy149ucXnmufd9KsyS84QVdWRO0e42xJo8=,iv:3pa/69eMSuJNxWxIeUHzD/sSvsJivsPShVJ6sxwn4NY=,tag:KJ7XHqMbEWDPR3qIu7gTpw==,type:str]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:8bVxbTWoKRX/SU5m1pu9825rFjhrafIqhNOGuyeEpRM=,iv:P8ZwLt7p4HICwwAqi4KYflU11p4i/8kx57SPZ7fTx4k=,tag:wJhf1G3mt4sOfEA0a88QAA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:o3zCRw==,iv:M9IHre8DPWQMmDh27Z9NFvJVvmjCgq4WtWmfscVbHzM=,tag:UlA3DCrP/0TMIZB5f4VgPA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:fwG+fC4nB4zSEgIgFDcI9sZnFIMXZZzysE1E5HMQZ1+4jLIP9KLmpQ==,iv:lC0U0Ho9OYRg6hSTeBnHlbKr94DWDqnzzrjGhO1bUOk=,tag:SMKqxUuVPxG1rOimVFpR+Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:o9VweQ==,iv:NtggT0wq8Og7dlZYlB6QTFzREDqWPi1IA2IPpj3Y6gg=,tag:O/be+I270WhNryxJm7l+6Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:bLVfv5cRfa2MmKhFXrMc9rDD0xIif7lPLbcJVULYVAun4P2e4tGOciEAizew4OKp,iv:Q9bVdchfDlZsPmqc/zFAkRZr+cZUzZ4BfCf1UGnAcb8=,tag:XzR1EIXFVVSRQgYVksjkUg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RcX5xNx860mUr+a2drsX,iv:bOXxuHbvY0Jvh/hEJztN0bPasFDk1v5cpFRV8P48bFs=,tag:CnNXZXijljTTOFH3WVBYeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTczBUOGhpaWhiMTFTOTBq
            WEN1NUkvS0dZKzFGKzJYalF0QWg4alpkVkNJCmZXd0NuQnArWUhWbGNZZDg1Y1Bu
            Ull4S1JJeG5FZGVjbG9QQUlxZlk1cU0KLS0tIENMdmtOdjJuMjNuTElVd3RVUEFH
            U28rZFg4VWxIUnFFY1VGdmRZWUlmeW8KqM9ESjZwhhjJNcCcILx1Bw3hRDKnbOkp
            I19r9vkSnNfNPpz7VM8pUB/NE7gJrEVC7IyVUvekuN+EzIlUN2VFAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T04:04:30Z"
    mac: ENC[AES256_GCM,data:8ShLnEEO/Lwt0ORgTCsqLmADzjWnOjOR5P37IgDwRc5hLi7ng/cDwJocC8AXej+dPNH2UeTom1CHMIS2N3BM+N70w4iaaRlrPvtrFEbKF1vvVuiltO8DeyzCQojPFQfBVc4Rwsu2VkNQOnfsGUeIsHnDC4BmKO3OkyAgTezfsl0=,iv:sIP2R5HyG0Vv5TJ4slL80wxF9KVQ9dlem9+ahfnqZKk=,tag:oyZMWz0ydP43WNzckFFYnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
