---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.3.3
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    localpv-provisioner:
      localpv:
        enabled: false
        image:
          registry: quay.io/
          repository: openebs/provisioner-localpv
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
          keep: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: true
      lvmNode:
        nodeSelector:
          openebs.io/lvmvg: "nvme"
      lvmController:
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: Exists
      lvmPlugin:
        allowedTopologgies: "kubernetes.io/hostname,openebs.io/lvmvg,"
    mayastor:
      enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
    engines:
      local:
        lvm:
          enabled: true
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
