# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: flux-system
stringData:
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:X2nwbkTZ848NmT2XnhdF,iv:JkHxbHupGs+mSac/A2oGz+8HH+5fjxWGcgCeKcKmpHU=,tag:Vt5ngKi9ZIqF6+oL4eEy5g==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:uaO2BIsxr5101Lgd8h4nH99PqnM=,iv:kpeua/bgXwbZ2Zy1TZamTDhEGGt3qH8ErPIxqrFVKmw=,tag:K3hazUkH5f9LpIGhxsRjkw==,type:str]
    FRIGATE_FRONT_PORCH_CAM: ENC[AES256_GCM,data:zNsc1ta14KRUH+u0A+zwrJTXfviIP9fZrpTzB+sETWdBfeBBaBwJ8JnixwcNL9AtVCsKeGE=,iv:9r1b3xVAusxpgc+BtPlqe4+NOARrN5kcYSCs7Q1g5Ws=,tag:IAKg01IuBvRYU/TtB5TTzg==,type:str]
    FRIGATE_DRIVEWAY_BACK_CAM: ENC[AES256_GCM,data:t2Ddv6m5zRfnke9u4HDCCqwHjdQ+A8/y,iv:y7yEPINmE9N6unGrEIxRFGmGUMn8SEMrM7Y0BktFddg=,tag:A13/Ln/Rb79ijaKOq4cwzQ==,type:str]
    FRIGATE_DRIVEWAY_FRONT_CAM: ENC[AES256_GCM,data:xFTlg5/H7QLj5gelMKZb0nUSSlkoVevKdcBUEVjRMxh6QoQABcNOIpC61WixHZQ2mWkK8zI=,iv:aCFBLVpqnXJRWodIJapX62JCy+ptQaN3a+IOcXn2hmo=,tag:57ZdxgkwPYdG40bkkD/gRQ==,type:str]
    FRIGATE_LEAN_TO_CAM: ENC[AES256_GCM,data:D/jWiMxhPdxqoJu7xraNr2y0kKaP4UBIN0I8nzW3kBnfNgl0CViArIDkWjHIxerm8IJZYC8=,iv:nr95y5wSUIVWE1xFL218EEp0AWHmsp0PfZb2kaF9oos=,tag:PvuPCNwkZPzfvUSx91D3uw==,type:str]
    FRIGATE_MAILBOX_CAM: ENC[AES256_GCM,data:rZadM2IyjZrnuGMsO5NkueDfC6XR1fvf,iv:i/nJxxrYc2MemomCuBvBlypFk16IR8B25sdbnlgkNds=,tag:OqsUiVjsQ8jXPWlrqWEDPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwh7am3lq020tgffrk80cvwkhqfh5jjl3u85um2gakgk234644qsxp3zw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraUU3dWFiS0lCRHViKy83
            SkFHbUtmTEJldG9VM0wzOHFCeTVSWG9sQkRzCmovRXZORkpIcTgwNHhacWdmREVU
            MnQ0Q0ZkNjRZU0t6andKdmdVZStlSDQKLS0tIFFRb3pQTGl1YlZCZUowZEFLNXNo
            OGtGZElMdHZ3d0xQV1J6ZkMvTldkejgKwgSQuz8go0j6uKQx2hI07obY/8YHdALF
            oEsLP9Jn4l0s3o1RAubDDTXx62rS0SfBHFdPWCTkp0c7ttWhMjxvNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-01T01:57:27Z"
    mac: ENC[AES256_GCM,data:BKkqnaYn3jqsXw0XyatBBb7nRbggQnS8nUT4I62oBcmRR4eXEYMP8P4wAeMoB9xyCKa1D4fBWKg+OGr//lgcsTjQWVFpZJVO8cVN4d1OiL+dnEAbJSmxjWLr99Bs01MWQfcE4iDPQzPL4+WwMchXBseETl5RImDrgEhBl8fS2Yo=,iv:MCQHztbhm8d5a7vzv8OAqlgrFjk3P/gZG16f35ivI8Y=,tag:B+dos60BjzstTBAtyJjM4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
