---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/lidarr
      tag: 2.1.7.4030@sha256:a09b22b63cefeb04f575b9ca10efb9e98a01b388120f7cd7c00005affabe8479
    env:
      TZ: "${TIMEZONE}"
    hostname: *app
    service:
      main:
        ports:
          http:
            port: 8686
    podSecurityContext:
      runAsUser: "${MEDIA_SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${MEDIA_SECURITY_CONTEXT_RUN_AS_GROUP}"
    persistence:
      config:
        enabled: true
        storageClass: zfs-nfs
        mountPath: /config
        size: 10Gi
      movies:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            path: "/warehouse/media/music"
            server: "${NFS_SERVER}"
        mountPath: /music
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:music
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
